"""
Fills Section 4 ("Medical Necessity Statement & Clinical Evidence") of
PA_Biological_Dressing_Template.docx with generated appeal evidence.

Only Section 4's rationale paragraph, its instructional callouts, and the PMID
evidence table are touched — every other section's placeholders (patient name,
DOB, wound measurements, physician signature, etc.) are left untouched for the
physician's office to complete manually. This function never receives or writes
patient-identifying data.

Locates content by matching the template's existing placeholder text rather than
by paragraph/table index, so it degrades gracefully (skips a section) if the
template is edited, instead of writing to the wrong place.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import BinaryIO, Union

import docx

logger = logging.getLogger(__name__)


def _replace_paragraph_text(paragraph, new_text: str) -> None:
    """Overwrite a paragraph's visible text, preserving its first run's formatting."""
    if not paragraph.runs:
        paragraph.add_run(new_text)
        return
    paragraph.runs[0].text = new_text
    for run in paragraph.runs[1:]:
        run.text = ""


def _find_paragraph(doc, *, starts_with: str):
    for p in doc.paragraphs:
        if p.text.strip().startswith(starts_with):
            return p
    return None


def _find_next_nonblank_paragraph(doc, marker_paragraph):
    # doc.paragraphs constructs a fresh list of Paragraph wrappers on every access,
    # so `is` identity comparison against a paragraph captured from an earlier call
    # never matches — compare the underlying lxml element instead, which is stable.
    hit_marker = False
    for p in doc.paragraphs:
        if p._p is marker_paragraph._p:
            hit_marker = True
            continue
        if hit_marker and p.text.strip():
            return p
    return None


def _find_evidence_table(doc):
    for table in doc.tables:
        if not table.rows:
            continue
        header = [c.text.strip() for c in table.rows[0].cells]
        if header[:2] == ["PMID", "Author(s), Journal, Year"]:
            return table
    return None


def fill_section4(
    template_path: Union[str, Path],
    output: Union[str, Path, BinaryIO],
    *,
    product: str,
    diagnosis: str,
    denial_reason_label: str,
    clinical_rationale: str,
    evidence_rows: list[dict],
    generated_at: str,
) -> None:
    """
    Write a copy of the template with Section 4 filled in.

    `output` may be a path (str/Path) or a writable binary stream (e.g. io.BytesIO)
    — the latter avoids any on-disk temp file, which matters for a multi-user
    Streamlit deployment.

    `evidence_rows` items need keys: pmid, citation, evidence_level, key_finding
    (matches the dict shape returned by WoundCareAgent.generate_appeal_evidence).
    """
    doc = docx.Document(str(template_path))

    step1 = _find_paragraph(doc, starts_with="▶  WOUND CARE SEARCH APP STEP 1")
    if step1 is not None:
        _replace_paragraph_text(
            step1,
            f"✅ Evidence auto-generated by the PA Appeal Builder on {generated_at} — "
            f"product: {product} · diagnosis: {diagnosis} · denial reason: {denial_reason_label}. "
            "Physician: verify against the patient's chart before submission.",
        )
    else:
        logger.warning("Section 4 STEP 1 placeholder not found — template may have changed.")

    rationale_label = _find_paragraph(doc, starts_with="Clinical Rationale:")
    if rationale_label is not None:
        rationale_body = _find_next_nonblank_paragraph(doc, rationale_label)
        if rationale_body is not None:
            _replace_paragraph_text(rationale_body, clinical_rationale)
    else:
        logger.warning("Section 4 'Clinical Rationale:' label not found — template may have changed.")

    step2 = _find_paragraph(doc, starts_with="▶  WOUND CARE SEARCH APP STEP 2")
    if step2 is not None:
        _replace_paragraph_text(
            step2,
            "Citations below were retrieved from PubMed (NCBI) automatically — "
            "attach the printed abstracts to this submission.",
        )

    table = _find_evidence_table(doc)
    if table is not None:
        for i, row_data in enumerate(evidence_rows[:3], start=1):
            if i >= len(table.rows):
                break
            cells = table.rows[i].cells
            _replace_paragraph_text(cells[0].paragraphs[0], row_data.get("pmid", ""))
            _replace_paragraph_text(cells[1].paragraphs[0], row_data.get("citation", ""))
            _replace_paragraph_text(cells[2].paragraphs[0], row_data.get("evidence_level", ""))
            _replace_paragraph_text(cells[3].paragraphs[0], row_data.get("key_finding", ""))
    else:
        logger.warning("Section 4 evidence table not found — template may have changed.")

    doc.save(output)
